### ISSUE TITLE
lodash.defaultsdeep error

### ISSUE THREAD

**Issue by jsauter** [vkbansal/gulp-edit-xml#4]
We install gulp-edit-xml in our applications and deploy it in production mode.  We get the error:

`Error: Cannot find module 'lodash.defaultsdeep'
November 21st 2019 09:15:46Error
    at Function.Module._resolveFilename (module.js:548:15)
November 21st 2019 09:15:46Error
    at Function.Module._load (module.js:475:25)
November 21st 2019 09:15:46Error
    at Module.require (module.js:597:17)
November 21st 2019 09:15:46Error
    at require (internal/module.js:11:18)
November 21st 2019 09:15:46Error
    at Object.<anonymous>`

I notice now you are installing lodash.defaultsdeep as a dev dependency in the package.json, but I think it is needed in the production code?

**Comment by vkbansal** [comment]
Thanks for reporting. Fixing it

**Comment by jsauter** [comment]
Thank you for the prompt fix.  We appreciate it!
